Constructor-io/constructorio-ui-autocomplete

- src/components/Autocomplete/SectionItemsList/SectionItemsList.tsx
- src/stories/Autocomplete/Hook/index.tsx
- src/styles.css
- Currently we will still show a section header even if there are no results to display.
- In order to prevent confusion, we should not show a section with 0 results
Before this PR:
With changes in this PR:
> Psl 1619 dont show sections that have 0 results

- .gitignore
- README.md
- package-lock.json
- package.json
- src/bundled.jsx
- vite.config.js
Users may now consume this library as a bundle via two ways:
`npm i '@constructor-io/constructorio-ui-autocomplete'`
```
import CioAutocomplete from '@constructor-io/constructorio-ui-autocomplete/constructorio-ui-autocomplete-bundled';
CioAutocomplete({
selector: '#autocomplete-container',
includeCSS: true, // Include the default CSS styles. Defaults to true.
apiKey: '',
onSubmit: (submitEvent) => console.dir(submitEvent),
// ... additional arguments
});
```
`<script type="module" src="./constructorio-ui-autocomplete-bundled.js"></script>`
```
window.CioAutocomplete({
selector: '#autocomplete-container',
includeCSS: true, // Include the default CSS styles. Defaults to true.
apiKey: '',
onSubmit: (submitEvent) => console.dir(submitEvent),
// ... additional arguments
});
```
> [CSL-2389] Adds option to consume library as a bundle

- src/hooks/useCioAutocomplete.ts
- src/hooks/useDownShift.ts
Tracking calls when blocked were causing unhandled error exceptions on code sandbox
> Error handling for tracking calls

- src/constants.ts
- src/hooks/useDebouncedFetchSections.ts
- src/stories/Autocomplete/Component/AdvancedParameters.stories.tsx
- src/stories/Autocomplete/Hook/AdvancedParameters.stories.tsx
- src/types.ts
Context
- let's give consumers of our lib the ability to customize the debounce delay  for autocomplete network requests
- motivation: [Mike and Ryan's feedback](https://constructor.slack.com/archives/C01F7U2BYGG/p1698353794756409?thread_ts=1698349445.798279&cid=C01F7U2BYGG)
What is the desired outcome?
- add support AND documentation for option to customize [os-ui-autocomplete debounce delay in useDebounce](https://github.com/Constructor-io/constructorio-ui-autocomplete/blob/c9568d9d44b8fce4d410377543ddb22b76f11f7a/src/hooks/useDebounce.ts#L4) for both the hook and component lib interface
> Psl 3022 os UI ac add optional advanced param for debounce delay

- .github/workflows/publish-create-github-release.yml
- .github/workflows/publish-npm.yml
- .github/workflows/publish.yml
- package-lock.json
- package.json
Adds some GH action based automations for publishing new versions of this package. Makes a small adjustment to the `version` npm script to accommodate these changes more cleanly (removes npm compile from this step since in the automation they are needed at different times). A detailed explanation of exactly what it should do follows:
* Triggered manually from the GitHub Actions UI (could also be done with scripts or GH API if desired in the future, see the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)  for this trigger type)
* Receives the version strategy to use for incrementing the new version (major, minor, patch)
* Receives the title to use for the new release, used in the GitHub release name
* Increments the …
> [PARTI-505] Add GH actions based automation for publishing

- src/hooks/useFetchRecommendationPod.ts
- src/stories/tests/ComponentTests.stories.tsx
- src/stories/tests/HooksTests.stories.tsx
- src/typeGuards.ts
The `isProduct` type guard was broken in [this PR](https://github.com/Constructor-io/constructorio-ui-autocomplete/pull/75/files#diff-9aea99b367f9871cb2e4c1a75340c75c63d6777954d9f882d06417d192d3894b). That PR incorrectly assumes anything outside of the `Products` section would be a non-product but that assumption is not correct. Recommendations would have a different section and could have an image. This PR reverts the type guard but also makes sure anything in `Search Suggestions` section will return false.
> [CSL-3029] Update isProduct type guard

- .github/workflows/publish-cdn.yml
- Adds the publish to CDN workflow from [this pr](https://github.com/Constructor-io/constructorio-ui-autocomplete/pull/103)
> [NO-REF] Add `publish-cdn` workflow

- src/constants.ts
- src/hooks/useCioAutocomplete.ts
- src/hooks/useCioClient.ts
- src/stories/Autocomplete/Component/index.stories.tsx
- src/stories/Autocomplete/Hook/index.stories.tsx
- src/types.ts
- src/utils.ts
Decided to call the parameter `cioJsCientOptions` to match the [types](https://github.com/Constructor-io/constructorio-client-javascript/blob/master/src/types/index.d.ts#L40).
> [CSL-3049] Add support for `cioJsClientOptions`

- package.json
To reproduce the error that was caused by the absence of this
- npx create-next-app@latest
- cd your-app
- npm i @constructor-io/constructorio-ui-autocomplete
- Create a component and paste in the following snippet (in thread)
- Observe error in ticket in import statement for useCioAutocomplete
> Explicitly export types path in package.json exports so it can be resolved

- src/types.ts
onSubmit event takes a union type as a parameter. Requiring that you add type guards before accessing any of the event object properties. Since this is a very common event. This PR Adds those type predicates with usage examples
> Add AutocompleteSubmitEvent type predicates

- src/utils.ts
Before
After
I think we should also revisit this function later because it assumes the starting string is camelCase but that's not always the case
> [NO-CSL] Update camelToStartCase function

- src/hooks/useCioAutocomplete.ts
- src/hooks/useFetchRecommendationPod.ts
- src/hooks/useSections.ts
- src/stories/Autocomplete/Hook/index.tsx
- src/stories/tests/ComponentTests.stories.tsx
- src/stories/tests/HooksTests.stories.tsx
- src/types.ts
- src/utils.ts
Recommendations Pod have a "display_name" attribute that we would want to render by default if available. If the user has specified a `displayName` configuration for the pod via the library, we should use that instead.
The css classnames should still reflect pod-id to avoid weird looking classnames such as `Best Sellers` rather than `best-sellers`.
- `useFetchRecommendationsPod` now returns an additional object `podsData` which contains both the `podId` and `displayName` returned by the response.
- Consequently, `utils/getActiveSectionsWithData` now takes in the `podsData` as a new optional parameter.
- In `getSectionProps` in `useCioAutocomplete`, `sectionTitle` is used setting classnames and should reflect `podId` rather than `displayName`
- In `SectionItemList`, `sectionTitle` here is …
> [CSL-3168] Surface the Display Name of Recommendations Pod by Default

- .storybook/custom-styles-story.css
- .storybook/full-example-styles-story.css
- README.md
- src/components/Autocomplete/SectionItemsList/SectionItemsList.tsx
- src/constants.ts
- src/hooks/useCioAutocomplete.ts
- src/stories/Autocomplete/Hook/index.tsx
- src/stories/tests/ComponentTests.stories.tsx
- src/stories/tests/HooksTests.stories.tsx
- src/styles.css
What this change include? 
- removes sentence cased classnames from section list items & moves to `data-cnstrc-display-name` 
- prefixes kebab cased classname like so `cio-section-kebab-case-item-section` 
- keeps main classname 
Before: 
After: 
- removes unnecessary classname from section item 
- task also includes criteria to "Make sectionName camelcase" but it already is 🤔
> [CSL-3088] - fix issue with conflicting styles

- .storybook/custom-styles-story.css
Styling fixes for text and images in Storybooks Hooks example
BEFORE
AFTER
> [OS-Autocomplete-UI] - Fix Recommendations Example

- src/constants.ts
- src/hooks/useCioAutocomplete.ts
- src/hooks/useFetchRecommendationPod.ts
- src/hooks/useRecommendationsObserver.ts
- src/hooks/useSections.ts
- src/stories/Autocomplete/Component/AdvancedParameters.stories.tsx
- src/stories/Autocomplete/Hook/AdvancedParameters.stories.tsx
- src/types.ts
* Add advancedParameters fetchZeroStateOnFocus to override the zero state fetching behavior from initial render to input focus
> [CI-3436] Autocomplete UI - Add an option to call zero state requests on focus

- src/components/Autocomplete/SectionItem/SectionItem.tsx
- src/styles.css
No breaking changes
Markup Before
Markup after
> Product suggestions are links by default

- src/components/Autocomplete/SectionItemsList/SectionItemsList.tsx
- src/constants.ts
- src/stories/Autocomplete/Component/Sections.stories.tsx
- src/types.ts
- src/utils.ts
Add an optional parameter to sections configuration for a custom `renderItem` function
> [CI-3883] Support custom pricing for product suggestions

- src/components/Autocomplete/SectionItemsList/SectionItemsList.tsx
- src/constants.ts
- src/stories/Autocomplete/Component/Sections.stories.tsx
- src/types.ts
- src/utils.ts
Support `getItemProps` so it can be used when calling a custom `renderItem` callback
> Support getItemProps for custom renderItem

- src/hooks/useCioAutocomplete.ts
- src/hooks/useNormalizedProps.ts
- src/types.ts
**Problem Statement**
1. We [memoized all props](https://github.com/Constructor-io/constructorio-ui-autocomplete/pull/158) to fix an issue with infinite rerenders when sections or zeroStateSections are passed directly to useCioAutocomplete as a literal array
2. This memoization introduced another issue where callback functions become stale
**Definition of Done:**
- Callback functions like `onSubmit` should have access to the most up-to-date values
- Passing object and array literals to `useCioAutocomplete` should not cause an infinite rerender
**How to reproduce:**
- add this to FullExampleTemplate in src/stories/Autocomplete/Component/index.TSX and then test on "Provide API Key" story
```
const [x, setX] = useState('123');
console.log(x); // This will have the most up to date value
const …
```
> Undo memoizing all of props options and only memoize Objects/Arrays

- src/components/Autocomplete/SearchInput/SearchInput.tsx
**Problem Statement:**
- On IOS devices interacting with autocomplete search input, a virtual keyboard appears with a "return" button (No call to action)
**Definition of done:**
- Update the search input mode to search so there's a "search" button (call to action)
**How to reproduce:** (You need an iPhone)
- Run storybook locally `npm run storybook:ci`
- Use ngrok to run `ngrok http http://localhost:6006`
- It will run a ngrok server and output a URL that you can open from your mobile device
> Update IOS devices virtual keyboard search input mode

- .github/workflows/deploy-storybook.yml
**Problem Statement**:
**The GitHub workflow responsible for deploying to Storybook failed**:
- Reason is GitHub [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) artifact actions
- While we don't use them directly, we use `upload-pages-artifact` which internally reference them
- `upload-pages-artifact` updated the deprecated artifacts on this version 
-  [v3.0.0](https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0)
- [The error](https://github.com/Constructor-io/constructorio-ui-autocomplete/actions/runs/13138775496/job/36661093955)
**Definition of done**
- Use `upload-pages-artifact@v3` This version is using the v4 artifact actions
- Use `deploy-pages@v4` since it's required with `upload-pages-artifact@v3`
> Fix deploy-storybook Github workflow

- src/components/Autocomplete/SectionItem/CustomSectionItem.tsx
- src/components/Autocomplete/SectionItemsList/SectionItemsList.tsx
- src/constants.ts
To test the custom HTMLElement as a return type for `renderItem` use this on `CustomRenderItem` item
```
renderItem: ({ item }) => {
const div = document.createElement('div');
const img = document.createElement('img');
img.src = item.data.image_url;
img.alt = item.value;
const name = document.createElement('div');
name.textContent = item.value;
const price = document.createElement('div');
price.textContent = item.data.price;
const button = document.createElement('button');
button.textContent = 'Add to Cart';
div.appendChild(img);
div.appendChild(name);
div.appendChild(price);
div.appendChild(button);
return div;
},
```
> Support renderItem in vanilla JS

- src/hooks/useCioAutocomplete.ts
- src/hooks/useCustomBlur.ts
- src/hooks/useDownShift.ts
- src/stories/tests/ComponentTests.stories.tsx
- src/stories/tests/HooksTests.stories.tsx
**Before** 
- The dropdown menu closes on Blur
**After**
- The dropdown menu closes on Blur AND click is not inside '.cio-autocomplete' element or its children
> Override default blur behavior

- src/hooks/useCustomBlur.ts
🐛  **The bug**
- The custom blur hook breaks the click events if and only uf `autocompleteClassName` consists of multiple class names, ie
- `cio-autocomplete custom-autocomplete-styles` 
🔁  **How to reproduce the bug?**
- Selects are broken on the full featured [example](https://constructor-io.github.io/constructorio-ui-autocomplete/?path=/story/autocomplete-component--full-featured-and-styled-example) since it has 
- `autocompleteClassName = 'cio-autocomplete custom-autocomplete-styles';`
✅ **The fix**
- Handle multiple class names by splitting and joining them again
> Fix custom blur

- README.md
Add a "Troubleshooting" section to the Readme to address common issues that may arise when utilizing the library.
> [CI-4261] New Docs: Add Troubleshooting Section to Readme

- .github/workflows/spell-check.yml
- package.json
* Added explicit version of `cspell` as the workflow was failing due to incompatible version of `node`
> [CDX-180] Add volta config to repo

- package-lock.json
- package.json
- src/utils/helpers.ts
The bug is that currently, you can’t listen to any of the dispatched events from the ConstructorIO client. Basically, this does not work.
`window.addEventListener('cio.client.autocomplete.getAutocompleteResults.completed', () => {});
`
This [line](https://github.com/Constructor-io/constructorio-client-javascript/blob/c280d29b1da6e04f5891045b9ace73c46b53576b/src/utils/event-dispatcher.js#L21) is the reason. waitForBeacon is true by default. Because we don’t load the beacon on OS UI AC the eventDispatcher remains inactive (active = false)
```
// If `waitForBeacon` option is set, only enable event dispatching once event is received from beacon
if (this.waitForBeacon) {
this.active = false;
}
```
To fix the bug we just need to pass this to the cio instance
```
const cioClient = new …
```
> Fix cio js client events not firing

- src/components/Autocomplete/SectionItem/SectionItem.tsx
- src/components/Autocomplete/SectionItemsList/SectionItemsList.tsx
* When variation_slicing is in place, there will be multiple items in the response with the same `item_id`.
* This causes React to have trouble differentiating components, leading to unexpected rendering behavior.
* Update key assignment to `SectionItem` to use `item?.data?.variation_id` as the primary key as `item.id` as the fallback
* This ensures uniqueness of key, whether variation_slicing is in place or not
* Removed `key` as an explicit prop in `SectionItemProps` and `SectionItemsListProps`
* The `key` field is a special prop that is used by React internally and it is not being passed down to the component as part of the props object. Such, there is no need to define it in the component props explicitly.
> [NOCI] Bugfix: Rendering More than Expected Number of Items

- src/hooks/useDownShift.ts
- src/stories/tests/ComponentTests.stories.tsx
- src/stories/tests/HooksTests.stories.tsx
- src/utils/tracking.ts
This pull request adds a new utility function for tracking recommendation selections and updates the `useDownShift` hook to use this new function. The main idea is that we have removing `SEARCH_TERM_STORAGE_KEY` in `src/tracker.js` in [autocomplete-ui](https://github.com/Constructor-io/autocomplete-ui/blob/master/src/tracker.js#L437C1-L438C1), but in this library, this part is missing. I added it here, so customers who use our autocomplete library don't face issues when we send the old search term by clicking on recommendations and adding to cart. 
Also, this PR improves how recommendation clicks are tracked, making the tracking logic more modular and reusable.
**Tracking improvements:**
* Added a new `trackRecommendationSelect` function to `src/utils/tracking.ts` to encapsulate …
> [CI-4786] Add removing search term on track recommendation click
